"""Hand-authored synthetic notice text. Not copied from agency letters."""

DISCLAIMER = (
    "This message is a synthetic example created for a sorting demonstration "
    "and is not an official VA, DFAS, or insurer notice."
)

CATEGORIES: list[dict] = [
    {
        "notice_type": "benefit_decision",
        "label": "ACTION_NEEDED",
        "suspicious": 0,
        "hard_case": "none",
        "source": "VA",
        "from_addrs": ["Example VA Regional Office <decisions@va.example.com>"],
        "subjects": [
            "Decision on your compensation claim, with a review deadline",
            "Rating decision issued, disagreement window is open",
            "Your award letter includes a date to challenge the rating",
            "Compensation decision ready, response window listed",
        ],
        "openers": [
            "The Example Regional Office finished a decision on the compensation claim in your demonstration file. The rating narrative and the monthly amount are both in the following paragraphs, and a clock is already running if you disagree.",
            "A reviewer at the Example Harbor Desk signed a disability compensation decision today. Please read the result carefully, because the time allowed to ask for another look is shorter than the life of the award.",
            "This letter records a new decision on service-connected compensation for the fictional veteran file used in this demo. The outcome is favorable in part, and the portion you may still challenge is described below.",
            "We issued the compensation decision that was waiting in the Example Ridge queue. The award can be paid while you decide whether the rating, the effective date, or both should be reviewed.",
        ],
        "middles": [
            "The decision grants a combined rating and sets the monthly compensation at $1,240.00 beginning February 1, 2026. One claimed condition was denied because the file, as it stands, does not connect that condition to service.",
            "Monthly compensation is awarded at $820.00. The effective date used is November 3, 2025, which is later than the date the claim was received, and that gap is the point a review would focus on.",
            "A partial grant sets compensation at $540.00 a month. The denied portion turns on a medical opinion already in the file; no new exam was ordered before the decision was signed.",
            "The rating increase was approved at $1,875.50 a month. An earlier inferred issue was left untouched, so the decision does not close every question that was raised in the claim.",
        ],
        "closings": [
            "If you disagree, a request for higher-level review must arrive by March 18, 2026. You may also file a supplemental claim with new evidence. This is a deadline, not a suggestion, and payments of the granted portion can continue while you choose.",
            "A notice of disagreement with the Board route, or a higher-level review, has to be submitted by April 2, 2026. After that date the decision stands on the record we have. Please respond by that day if the rating does not look right.",
            "You must submit any request for another review no later than May 7, 2026. Appeal rights are printed so they are not missed. Missing the date means the denied portion will not be reopened on this same record.",
            "The response window closes on June 12, 2026. Action needed: tell the Example Regional Office whether you accept the decision or you want it reviewed. A phone call alone does not preserve the deadline.",
        ],
    },
    {
        "notice_type": "benefit_decision",
        "label": "INFORMATIONAL",
        "suspicious": 0,
        "hard_case": "none",
        "source": "VA",
        "from_addrs": ["Example VA Regional Office <awards@va.example.com>"],
        "subjects": [
            "Confirmation that your compensation award continues",
            "Decision complete, no reply is requested",
            "Your monthly award is unchanged this quarter",
            "Award letter for your records, nothing to send back",
        ],
        "openers": [
            "This note confirms a decision that is already in effect on the fictional compensation file. Nothing in it asks you to mail a form or to call before a date.",
            "The Example Cedar Desk completed a routine decision review and found the current award should keep running. We are sending the explanation so your records match ours.",
            "A cost-of-living adjustment was applied to the demonstration award. The letter is for your information and does not open a new claim.",
            "We wrote to summarize a decision that granted the pending issue in full. The file is current, and this copy is the one to keep with your papers.",
        ],
        "middles": [
            "Monthly compensation remains $1,050.00. The payment date, the direct-deposit destination already on file, and the combined rating are unchanged from last month.",
            "The decision agrees with the exam that was already of record. No condition was denied in this action, so there is no separate disagreement path attached to this particular letter.",
            "The updated monthly amount is $675.25 after the annual adjustment. You will see the new figure on the next regular deposit. No form was enclosed.",
            "Dependent status on the file was confirmed from documents you sent last year. The decision does not add or remove anyone, and the rate stays at $412.80 a month.",
        ],
        "closings": [
            "No action is required. No response is needed to keep the award in force. For your information, later letters will say so plainly if a deadline ever applies.",
            "Please file this confirmation with your records. No response needed. If a future decision limits the award, that later letter will explain any review period on its own.",
            "This is informational. You do not have to call, visit, or send evidence because of this message. The next deposit should appear on the usual day.",
            "Keep this page for your files. No action required to continue compensation. We will write again only if the award itself changes.",
        ],
    },
    {
        "notice_type": "debt_overpayment",
        "label": "ACTION_NEEDED",
        "suspicious": 0,
        "hard_case": "none",
        "source": "VA",
        "from_addrs": ["Example Debt Management Center <dmc@va.example.com>"],
        "subjects": [
            "Overpayment on your compensation, balance due",
            "A debt was created after a payment review",
            "Debt notice: withholding can start if you do nothing",
            "Please resolve this compensation overpayment",
        ],
        "openers": [
            "The Example Debt Management Center completed a review of compensation paid on the demonstration file and found that too much was released.",
            "An audit of the fictional award created a debt. This letter is the notice of that overpayment and of the ways to address it before money is taken from later payments.",
            "We are writing because a portion of compensation paid after a change in dependent status was not due. The extra amount is now a debt on the example account.",
            "A reconciliation showed an overpayment of compensation. The debt is collectible, and you have a short period to pay, to request a waiver, or to ask for a payment plan.",
        ],
        "middles": [
            "The balance due is $2,430.00. It covers compensation released from August 2025 through October 2025 after a dependent was removed and the rate was not reduced in time.",
            "The debt amount is $860.40. It is the difference between the rate paid and the rate the later decision says applied. No interest figure is included in this demo letter.",
            "Our ledger shows $1,240.00 past due. If the debt is not resolved, up to the allowed share of future compensation can be withheld until the balance is gone.",
            "The overpayment totals $540.00. The notice explains the months involved and the rate that should have been used. A payment coupon is described in the envelope of this fictional mailing.",
        ],
        "closings": [
            "Action required: pay the debt, request a waiver, or set up a plan by March 9, 2026. You must respond by that date if you do not want withholding to begin on the following payment.",
            "The amount due should be settled by April 16, 2026. A waiver request needs a short statement of why collection would be unfair. Silence is treated as agreement to collect.",
            "Please reply by May 1, 2026 and choose payment, waiver, or a monthly plan. This debt will not disappear if the letter is set aside. Help is available from the example office that sent it.",
            "No later than June 4, 2026, tell us how the overpayment should be handled. Action needed before withholding starts. A phone message without the written choice does not stop the collection.",
        ],
    },
    {
        "notice_type": "premium_due",
        "label": "ACTION_NEEDED",
        "suspicious": 0,
        "hard_case": "none",
        "source": "VGLI",
        "from_addrs": ["Example VGLI Servicing <billing@insurance.example.com>"],
        "subjects": [
            "Your VGLI premium is due",
            "Life insurance premium bill for the example policy",
            "Please pay the VGLI premium for this period",
            "Premium statement: amount due on the demonstration policy",
        ],
        "openers": [
            "Example VGLI Servicing is sending the premium bill for the fictional Veterans' Group Life Insurance policy in this demo. The coverage amount on file has not changed.",
            "This is the regular premium notice for the example life insurance policy administered in this dataset as a stand-in for VGLI. The policy stays active when the premium is paid on time.",
            "A new premium period opened on the demonstration VGLI policy. The bill below is the amount that keeps the same coverage in force.",
            "We bill the example policy once each period. This message is that bill, addressed to the fictional policyholder and not to a real person.",
        ],
        "middles": [
            "The premium due is $86.40 for the period that starts March 1, 2026. The coverage amount shown on the example policy is unchanged, and no loan is attached to this bill.",
            "Please pay $118.40. That figure is the current premium for the coverage tier on the demonstration policy. A prior credit of zero is applied.",
            "The amount due this period is $64.25. It is higher than the last bill because the example policy moved into the next age band. Coverage itself is the same.",
            "This period's premium is $146.75. The bill does not include any extra rider. Only the base example VGLI coverage is being continued.",
        ],
        "closings": [
            "Pay the premium due by March 20, 2026 so the policy does not rely on a grace period. You can send a check to the example lockbox or use the payment instruction already on file. Action required if you want the period paid in full.",
            "The premium should arrive by April 8, 2026. If you already mailed it, you can ignore a crossing in the mail. Otherwise this amount due still needs to be paid.",
            "Please submit payment no later than May 14, 2026. Keeping the same bank draft on file is fine if the draft is still valid. A failed draft will produce a separate letter.",
            "Action needed: the premium is due by June 2, 2026. Partial payment does not complete this period. The example servicing office can explain a plan only if you contact them before the due date.",
        ],
    },
    {
        "notice_type": "lapse_warning",
        "label": "ACTION_NEEDED",
        "suspicious": 0,
        "hard_case": "none",
        "source": "VGLI",
        "from_addrs": ["Example VGLI Servicing <retention@insurance.example.com>"],
        "subjects": [
            "VGLI coverage will end unless the premium arrives",
            "Grace period is open on the example life policy",
            "Lapse warning for your demonstration VGLI policy",
            "Final notice before the example policy lapses",
        ],
        "openers": [
            "Example VGLI Servicing has not received the last premium on the fictional policy. Coverage is inside a grace period and will not continue by default.",
            "This is a lapse warning, not a routine bill. The demonstration life policy is still in force only because the grace period has not finished.",
            "We did not post a premium for the latest period on the example VGLI policy. Without payment, the policy is scheduled to end.",
            "The fictional policyholder is inside the last stretch of the grace period. We are writing so the end date is not a surprise.",
        ],
        "middles": [
            "The unpaid premium is $86.40. The grace period that protects the example coverage ends on March 28, 2026. After that date a missed payment is not given extra days in this scenario.",
            "Coverage will end on April 19, 2026 if $118.40 is not posted. The warning is tied to one unpaid period, not to a change in health.",
            "The grace period closes May 22, 2026. The amount that restores the current period is $64.25. No separate reinstatement fee is invented for this demo.",
            "On June 15, 2026 the example policy lapses if $146.75 remains unpaid. A lapsed policy in this scenario does not pay a claim for a later date of death.",
        ],
        "closings": [
            "Action required: pay before the grace period ends if you want the coverage to stay in force. Write the policy reference as 'example policy' rather than a number. A lapse is avoidable only before the date above.",
            "You must submit the premium before coverage will end on the date in this letter. Calling to promise a payment does not extend the grace period in this example.",
            "Please pay now so the policy does not lapse. If the coverage should end, tell the example office explicitly; silence is treated as a missed premium, not as a cancellation request.",
            "This lapse warning needs a payment or a clear instruction before the end date. Action needed. After the grace period, a new application would be required in this fictional program, and acceptance is not guaranteed.",
        ],
    },
    {
        "notice_type": "appointment_reminder",
        "label": "ACTION_NEEDED",
        "suspicious": 0,
        "hard_case": "none",
        "source": "VA",
        "from_addrs": ["Example VA Clinic <appointments@va.example.com>"],
        "subjects": [
            "Please confirm your appointment at the Example clinic",
            "Clinic appointment coming up, reply if you cannot attend",
            "Your visit is on the calendar and needs a confirmation",
            "Reminder: confirm or reschedule the Example clinic visit",
        ],
        "openers": [
            "The Example Cedar Annex Clinic scheduled a visit on the fictional chart. This reminder asks you to confirm that you can attend or to move the visit.",
            "A clinician at Example Harbor Annex is holding a slot for a follow-up. The appointment is not complete until you confirm or reschedule.",
            "This is a reminder from Example Ridge Clinic about an upcoming visit on the demonstration schedule. Unconfirmed slots are released.",
            "Example North Clinic sent this note because a visit is approaching and the scheduling desk does not yet have a confirmation.",
        ],
        "middles": [
            "The visit is on March 11, 2026 at 9:30 in the morning, for a primary-care follow-up. Plan on a lab draw if you have not had one this quarter. Arrive a few minutes early for the example front desk.",
            "Please come on April 7, 2026 at 1:15 in the afternoon for audiology. The slot is 40 minutes. Bring a list of current medicines; do not bring original discharge papers.",
            "You are booked on May 19, 2026 at 10:00 in the morning for a compensation exam at the example clinic, not at a private office. The examiner will already have the claim summary.",
            "The diabetes check is June 8, 2026 at 3:00 in the afternoon. Fasting is not requested. A nurse visit is included in the same slot.",
        ],
        "closings": [
            "Please confirm your appointment by replying to this example mailbox or by calling the clinic desk. If you need to reschedule, do it before March 9, 2026 so another veteran in the demo queue can use the slot. Action required.",
            "Confirm you will attend, or reschedule, by April 3, 2026. A missed visit without notice is marked as a no-show on the example chart. You must tell the desk if the time does not work.",
            "Action needed: confirm or change the visit no later than May 15, 2026. Transportation help for the example clinic has to be requested at the same time, not on the morning of the visit.",
            "Please reply by June 4, 2026. Keeping the appointment is the default only if you confirm. Otherwise the slot goes back to the schedule and you will wait for a new one.",
        ],
    },
    {
        "notice_type": "appointment_notice",
        "label": "INFORMATIONAL",
        "suspicious": 0,
        "hard_case": "none",
        "source": "VA",
        "from_addrs": ["Example VA Clinic <clinic-news@va.example.com>"],
        "subjects": [
            "Example clinic hours on the next holiday",
            "After-visit summary from your completed appointment",
            "The lab booth location changed inside the example clinic",
            "Reminder of clinic parking rules, no visit is scheduled",
        ],
        "openers": [
            "Example Cedar Annex Clinic is sharing a facilities note. It does not create, move, or cancel a personal appointment.",
            "This after-visit summary covers a demonstration appointment that has already happened. No further visit is being scheduled by this message.",
            "A hallway project at Example Ridge Clinic changed where the lab booth sits. Your future visits, if you have any, are not being rescheduled here.",
            "The example clinic is sending a short bulletin about parking. It is not a reminder of a booked visit.",
        ],
        "middles": [
            "On February 16, 2026 the clinic closes for a staff training day. Emergency care for the demo campus is directed to the usual after-hours nurse line. Routine desks reopen the next morning.",
            "At the completed visit the nurse recorded blood pressure and reviewed medicines already on the chart. No new prescription was started. The note is available in the example health record.",
            "The lab booth moved from the first floor lobby to room 12 on the second floor of the example clinic. Signs are posted. You do not need an appointment solely because of the move.",
            "Visitor parking at the example garage now asks for the paper slip to be placed on the dash. The rule starts March 2, 2026 and applies whenever you happen to visit. No visit was added for you.",
        ],
        "closings": [
            "No action is required by this hours notice. For your information only. If you already have a separate appointment letter, follow that letter rather than this bulletin.",
            "No response is needed to file this after-visit summary. It does not ask you to book anything. Contact the clinic only if the completed-visit note disagrees with what you remember.",
            "This location note is informational. No action required. You do not have to confirm a slot, because no slot was booked by this message.",
            "File the parking bulletin if you like. No response needed. It will not affect compensation, insurance, or any claim.",
        ],
    },
    {
        "notice_type": "claim_evidence",
        "label": "ACTION_NEEDED",
        "suspicious": 0,
        "hard_case": "none",
        "source": "VA",
        "from_addrs": ["Example VA Regional Office <claims@va.example.com>"],
        "subjects": [
            "We still need evidence before the claim can move",
            "Your claim is paused for a missing record",
            "Please send the employment dates the rater asked for",
            "Evidence request with a due date on the example claim",
        ],
        "openers": [
            "The rater on the fictional claim cannot finish without one more item. Development is paused until that evidence arrives or the date below passes.",
            "Example Regional Office opened an evidence request on the demonstration claim. The claim is not denied; it is waiting.",
            "A review of the example claim found a gap. We are asking for the missing piece now so the decision is not made on an incomplete file.",
            "This is a development letter. The fictional claim stays open, and the next step belongs to you or to the records office you authorize.",
        ],
        "middles": [
            "Please send the dates of civilian employment from 2014 through 2016, even if the employer no longer exists. A short signed statement is enough in this demo. We do not want a full personnel file.",
            "The private hospital records from the example city's clinic were not included. A release limited to the 2022 visit would let us request them. Do not mail original films.",
            "We need the separation narrative you mentioned and do not yet see. A copy is fine. The claim can use a certified copy or a clear scan in the example upload portal.",
            "The examiner quoted a medication list that is not in the file. Send the current list with doses. You do not need a new physical for this particular request.",
        ],
        "closings": [
            "Submit the evidence by March 27, 2026. You must reply by then if you want it considered. After the date, the rater may decide on what is already here. Action required.",
            "The evidence is due by April 21, 2026. A statement that you have nothing further also counts as a response and lets the claim move. Silence keeps the file in suspense until the date, then it moves without the item.",
            "Please send the record no later than May 29, 2026. If a provider is slow, tell us before the deadline so the example office can note the delay. Otherwise the decision will not wait.",
            "Action needed by June 18, 2026. That is the last day this evidence request stays open. Include your example file label in the corner of the page and do not include any government identifier number.",
        ],
    },
    {
        "notice_type": "claim_status",
        "label": "INFORMATIONAL",
        "suspicious": 0,
        "hard_case": "none",
        "source": "VA",
        "from_addrs": ["Example VA Regional Office <status@va.example.com>"],
        "subjects": [
            "We have received your claim",
            "Status update: the example claim is still processing",
            "Your claim moved to the rating queue",
            "No new documents are requested right now",
        ],
        "openers": [
            "This status note describes where the fictional claim sits. It does not ask for a form, a fee, or a phone call.",
            "Example Regional Office is confirming receipt activity on the demonstration claim. The message is a snapshot, not a decision.",
            "The example claim changed queues. We send these notes so the wait is visible. Nothing is due from you because of this one.",
            "A processing update was generated for the fictional file. Read it as a status, not as a task.",
        ],
        "middles": [
            "We have received the claim package that was submitted in January. It is in the initial review queue. No one has been assigned as the rater yet.",
            "The claim is still processing. A medical exam was completed last week and the results are in the file. The next step is internal.",
            "The file moved from development to the rating queue on March 4, 2026. No further evidence is being requested in this update.",
            "A duplicate upload of a document you already sent was ignored automatically. The claim content is unchanged and is still processing.",
        ],
        "closings": [
            "No action is required. No response needed to keep your place in the queue. We will write a separate letter if evidence is actually missing.",
            "For your information, waiting is the correct step. Do not send another copy of the same claim. A decision letter, when it exists, will say so in the subject.",
            "This status update does not set a deadline. No action required. Checking again next week will not move the example queue.",
            "No response is needed. If a later letter sets a date, that letter replaces this status note. Until then, the claim remains in process.",
        ],
    },
    {
        "notice_type": "address_verification",
        "label": "ACTION_NEEDED",
        "suspicious": 0,
        "hard_case": "none",
        "sources": ["VA", "DFAS"],
        "from_addrs": [
            "Example VA Regional Office <address@va.example.com>",
            "Example myPay <address@dfas.example.com>",
        ],
        "subjects": [
            "Please verify your mailing address",
            "Address verification needed before the next payment",
            "Confirm the address on the example file",
            "We need a current address to keep payments moving",
        ],
        "openers": [
            "The address on the fictional file has not been confirmed in more than a year. Payments and letters both use it, so a check is due.",
            "A piece of example mail was returned by the postal service. We need a current address before the next notice is sent.",
            "Example myPay and the example benefits file share a mailing address in this demo. One of them failed a postal check.",
            "This is an address verification request on the demonstration account. It is not a request for a bank password or a government identifier.",
        ],
        "middles": [
            "The address we have is a street in the fictional town of North Example. If you still receive mail there, a simple confirmation is enough. If you moved, send the new street, city, and ZIP.",
            "The returned envelope did not include a forwarding sticker. Until you verify your address, paper notices will be held in the example queue rather than remailed.",
            "Direct deposit can continue to the bank already on file, but the postal address still has to be current for tax statements and decision letters. Those are separate fields.",
            "We will not ask you to read a code aloud or to type a password. The only fact needed is whether the mailing address is right.",
        ],
        "closings": [
            "Verify your address by March 13, 2026. Action required so payments are not delayed. Reply with 'address correct' or with the new address. Do not include an account number.",
            "Please confirm the mailing address no later than April 9, 2026. If we do not hear from you, paper mail pauses. Electronic deposit is not a substitute for this confirmation.",
            "You must reply by May 6, 2026. Address verification is the whole task. A relative can mail the confirmation if you sign it.",
            "Action needed by June 10, 2026: tell us the address is right or replace it. After that date the example file is marked unverified and some notices stop.",
        ],
    },
    {
        "notice_type": "mypay_account",
        "label": "ACTION_NEEDED",
        "suspicious": 0,
        "hard_case": "none",
        "source": "DFAS",
        "from_addrs": ["Example myPay <alerts@dfas.example.com>"],
        "subjects": [
            "Direct deposit was returned by the bank",
            "Update your direct deposit on the example myPay file",
            "A retired-pay payment was rejected",
            "Action needed on the example myPay destination account",
        ],
        "openers": [
            "Example myPay tried to release retired pay on the fictional account and the bank sent it back.",
            "The demonstration direct deposit was rejected. Until the destination is updated, the payment sits as an unclaimed credit in the example system.",
            "A change at the bank, not a change in entitlement, stopped the last retired-pay deposit in this scenario.",
            "We are writing from example myPay because the payment instruction on file did not work.",
        ],
        "middles": [
            "The returned amount is $1,875.50. The bank reason in this demo is 'account closed'. The entitlement itself was not reduced.",
            "Payment of $820.00 was rejected on the March cycle. No replacement check has been cut yet. The money is waiting for a new destination.",
            "The example pay system received a return for $540.00 marked 'unable to locate account'. We will not guess a new account.",
            "A deposit of $675.25 did not post. The rejection arrived two business days after the release. The pay calendar for next month is still open.",
        ],
        "closings": [
            "Update your direct deposit by March 17, 2026. Action required. Use the example myPay site you already sign in to, and do not send account digits in a reply to this letter.",
            "You must correct the payment instruction no later than April 14, 2026 if you want the returned amount reissued on the next cycle. A paper check is the fallback only after that update fails.",
            "Please submit the new direct-deposit instruction by May 12, 2026. Action needed before the credit is held for manual review. Phone calls cannot capture a routing number in this demo process.",
            "Reply through the example myPay profile by June 9, 2026. The returned payment will not be re-sent to the same closed destination. This deadline is about where the money goes, not about whether it was earned.",
        ],
    },
    {
        "notice_type": "mypay_1099",
        "label": "INFORMATIONAL",
        "suspicious": 0,
        "hard_case": "none",
        "source": "DFAS",
        "from_addrs": ["Example myPay <statements@dfas.example.com>"],
        "subjects": [
            "Your example 1099-R is now available",
            "Tax statement ready in example myPay",
            "The retired-pay statement for last year is posted",
            "1099-R posted for your records, no change was requested",
        ],
        "openers": [
            "Example myPay posted the annual tax statement for the fictional retired-pay account. This note says where to read it.",
            "The demonstration 1099-R for last year is ready. We are not asking you to change withholding in this message.",
            "A tax statement was added to the example document list. It replaces nothing you have to sign.",
            "This is the availability notice for the example 1099-R. It is not a bill and not a debt letter.",
        ],
        "middles": [
            "The statement summarizes retired pay posted during the prior calendar year on the demonstration account. The total is $14,400.00. Withholding shown there matches what was already taken.",
            "You can download the 1099-R from the statements tab of example myPay. The form uses the mailing address already verified. No new address is requested here.",
            "The posted statement shows gross pay and the amount withheld for federal tax. It does not calculate what you owe. A tax preparer, if you use one, should read the form itself.",
            "Last year's statement is now available alongside the monthly advice of pay. The monthly slips were not changed by this posting.",
        ],
        "closings": [
            "No action is required to keep retired pay going. For your information, the statement will remain available in the example account. This letter does not set a filing deadline with any tax authority.",
            "No response needed. If the figures look wrong, the example myPay help page explains how to ask for a review, and that request would be a separate process.",
            "This availability note is informational. You do not have to reply. Downloading the form is optional until you are ready to prepare taxes.",
            "No action required by example myPay because of this posting. Keep the statement with your tax papers if you wish.",
        ],
    },
    {
        "notice_type": "newsletter",
        "label": "INFORMATIONAL",
        "suspicious": 0,
        "hard_case": "urgent_newsletter",
        "source": "VA",
        "from_addrs": ["Example VA News <news@va.example.com>"],
        "subjects": [
            "Urgent: do not miss this month's benefits bulletin",
            "Act now to read the example enrollment tips",
            "Time-sensitive newsletter: health coverage myths",
            "Urgent update from Example VA News, for readers only",
        ],
        "openers": [
            "Urgent wording is intentional in this bulletin, and it still is only a newsletter. Nothing in it is a personal deadline on a claim, a debt, or a policy.",
            "Act now is how this demo edition opens, because real bulletins sometimes sound that way. The pages that follow are general tips, not a task on your file.",
            "This urgent-looking note is the monthly example newsletter. It was sent to the whole demonstration list, not because a rater is waiting on you.",
            "Do not miss the enclosed explainer, the subject line says. The explainer is an article. It does not change your award, your premium, or your appointment book.",
        ],
        "middles": [
            "The article compares community-care myths with the way referrals actually work in the example system. It mentions no individual claim and asks for no document.",
            "A short piece lists questions to ask at a routine visit. It is written for any reader. It does not confirm that you have a visit booked.",
            "The bulletin describes how a higher-level review differs from a supplemental claim in general terms. It is education, not an invitation tied to a decision in your name.",
            "This edition collects three reminders about keeping copies of letters. It does not say that any letter of yours is missing.",
        ],
        "closings": [
            "No action is required. This is a newsletter. Unsubscribe at news.example.com/unsubscribe if you do not want the example bulletin. For your information only.",
            "No response is needed, even though the subject said urgent. Unsubscribing is optional and does not affect benefits. The example newsroom will send the next edition on the usual schedule.",
            "Newsletter only: no action required to protect a payment or a policy. You can ignore the urgent tone. The unsubscribe link is https://news.example.com/unsubscribe and it is not a login page.",
            "For your information. No deadline applies to you because of this mailing. If a real decision later needs a reply, it will arrive as its own letter and will not look like this bulletin.",
        ],
    },
    {
        "notice_type": "newsletter",
        "label": "INFORMATIONAL",
        "suspicious": 0,
        "hard_case": "none",
        "source": "VA",
        "from_addrs": ["Example VA News <digest@va.example.com>"],
        "subjects": [
            "Example VA News monthly digest",
            "This month's quiet digest from the example newsroom",
            "Stories from the demonstration benefits bulletin",
            "Monthly reader, no task inside",
        ],
        "openers": [
            "The calm edition of Example VA News is a digest of public-style stories. It is not tied to the fictional file's claims or payments.",
            "Readers on the example list receive this digest once a month. It has no personal balance and no appointment time.",
            "This edition leads with a profile of a fictional volunteer driver and a note about clinic gardens. Neither item asks for a reply.",
            "We collected three short reads for the demonstration newsletter. They are background, not instructions on an open claim.",
        ],
        "middles": [
            "The volunteer-driver profile describes a route between two example clinics. No recruitment form is attached. The garden note lists which vegetables the demo beds grew.",
            "A sidebar explains how to read a general benefits pamphlet. It does not say your pamphlet is out of date, and it does not name a form you must return.",
            "The digest mentions that example town halls happen in the spring. No seat was reserved for you. Dates in the article are illustrative.",
            "One article talks about organizing papers at home. It is generic advice. It does not claim that your address, your deposit, or your premium is wrong.",
        ],
        "closings": [
            "No action is required. Unsubscribe any time at https://digest.example.com/unsubscribe. For your information.",
            "This newsletter does not need a response. Missing an edition has no effect on compensation or insurance. The next digest arrives next month.",
            "No response needed. You are on the example reader list only. Leaving the list is optional and is not reported to any rater.",
            "File or delete the digest as you like. No action required. It will never be the vehicle for a debt notice or a decision deadline.",
        ],
    },
    {
        "notice_type": "survey",
        "label": "INFORMATIONAL",
        "suspicious": 0,
        "hard_case": "none",
        "source": "VA",
        "from_addrs": ["Example VA Surveys <surveys@va.example.com>"],
        "subjects": [
            "Optional survey about a recent example clinic visit",
            "Your feedback is invited, and it is optional",
            "A short questionnaire on the demonstration visit",
            "Tell us about the example waiting room, if you want",
        ],
        "openers": [
            "Example VA Surveys invites feedback on a fictional visit. The invitation is optional and is not part of the medical record.",
            "A questionnaire was opened because the demonstration schedule shows a completed visit. Skipping it has no consequence.",
            "We would like your feedback on the example clinic's front desk. The note is a survey request, not a follow-up order.",
            "This message asks whether you will answer a few questions. It does not schedule care and it does not decide a claim.",
        ],
        "middles": [
            "The optional survey has six questions about wait time and whether the clinician explained the plan. It does not ask for a government identifier or a password.",
            "Your feedback would cover the signs in the example lobby and the ease of finding the lab booth. Answers are not tied to payment.",
            "The questionnaire takes about four minutes. None of the items ask you to dispute a bill, confirm a debt, or verify an address.",
            "If you start the survey and stop, the partial answers are discarded in this demo. There is no penalty and no second deadline.",
        ],
        "closings": [
            "The survey is optional. No action is required. If you want to answer, the form is at https://surveys.example.com/visit and it closes for this wave on April 30, 2026 without affecting benefits.",
            "No response is needed. Choosing not to answer will not delay a claim, a deposit, or a prescription. The link, if you use it, is https://surveys.example.com/desk.",
            "For your information, feedback is welcome and silence is fine. This is not action required. The example survey desk does not send collections.",
            "You can ignore this invitation completely. No action required to stay in good standing with the example clinic, the regional office, or the insurer.",
        ],
    },
    {
        "notice_type": "premium_receipt",
        "label": "INFORMATIONAL",
        "suspicious": 0,
        "hard_case": "none",
        "source": "VGLI",
        "from_addrs": ["Example VGLI Servicing <receipts@insurance.example.com>"],
        "subjects": [
            "We received your VGLI premium",
            "Payment posted on the example life policy",
            "Thank you, the demonstration premium is in",
            "Receipt for the latest VGLI premium payment",
        ],
        "openers": [
            "Example VGLI Servicing posted a premium payment on the fictional policy. This letter is the receipt.",
            "The latest premium reached the example lockbox and was applied. Coverage for the current period is paid.",
            "We are confirming that the demonstration policy is paid through the present period. No balance is being billed here.",
            "A payment posted to the example life policy. The receipt is for your records.",
        ],
        "middles": [
            "Payment of $86.40 posted on March 3, 2026. It covers the period that started March 1. The coverage amount is unchanged.",
            "We applied $118.40 to the current period. The example policy shows no past-due premium after this posting.",
            "The draft for $64.25 cleared. Thank you for your payment. The next bill, when it exists, will be a separate letter.",
            "A check for $146.75 was deposited and applied. The grace period is not in use. Nothing is late.",
        ],
        "closings": [
            "No action is required. For your information, keep this receipt with the policy papers. You do not need to call to confirm the posting.",
            "No response needed. The payment was received and the period is covered. A later lapse warning would only be sent if a future premium were missed.",
            "This receipt is informational. No action required to keep the paid period in force. The example office will not call to ask for a password because of a receipt.",
            "File the receipt if you keep paper records. No response is needed. The policy continues for this period without another step.",
        ],
    },
    {
        "notice_type": "polite_deadline",
        "label": "ACTION_NEEDED",
        "suspicious": 0,
        "hard_case": "polite_deadline",
        "sources": ["VA", "DFAS", "VGLI"],
        "from_addrs": [
            "Example VA Regional Office <courtesy@va.example.com>",
            "Example myPay <courtesy@dfas.example.com>",
            "Example VGLI Servicing <courtesy@insurance.example.com>",
        ],
        "subjects": [
            "A quiet note about a date on your example file",
            "When you have a moment, a window is closing",
            "Courtesy reminder before the example file moves on",
            "We can still add a page, for a little while",
        ],
        "openers": [
            "Hello. We hope this note is easy to set aside until you have a free minute. It still has a date on it, and the date matters.",
            "Good morning. The example office finished a quiet review and wanted to tell you in a low-key way. There is a closing date underneath the courtesy.",
            "We are glad to write gently. The fictional file is in good shape except for one page that is not here yet.",
            "Thank you for your patience with the demonstration file. This letter is polite on purpose. Please do not read the tone as 'nothing is due'.",
        ],
        "middles": [
            "The only missing page is a short note of the months you worked for the example city school. The rest of the file is complete enough to rate, and the rater will use it as it stands once the window ends.",
            "A bank name on the example retired-pay profile looks out of date. We can still correct the destination before the next cycle is locked. After the lock, the old instruction is what the system will try.",
            "The example life policy can still list a different beneficiary. The form is a single page. If it does not arrive, the beneficiary already printed stays in place.",
            "One dependent's date of birth on the demonstration compensation file was left blank. The rate for the current month does not include that person until the date is filled in.",
        ],
        "closings": [
            "Whenever it is convenient, please send the page. The response window closes on March 25, 2026, and after that the file may be finished without it. We would rather have your note than guess.",
            "At your convenience, update the destination. The last day we can take the change for the coming cycle is April 11, 2026. A later note is still welcome and would apply to the cycle after that.",
            "If you would like the new beneficiary considered, the page needs to be here by May 20, 2026. There is no harsh penalty language in this letter; the practical effect is that the old choice remains.",
            "When you have a moment before June 6, 2026, send the missing date of birth. That is the last day this courtesy hold stays open. We will proceed kindly, and we will proceed on the file as it is.",
        ],
    },
    {
        "notice_type": "phishing_demand",
        "label": "ACTION_NEEDED",
        "suspicious": 1,
        "hard_case": "phishing",
        "source": "VA",
        "from_addrs": ["Benefits Security <security@va-notice.example.com>"],
        "subjects": [
            "Your benefits were suspended, verify today",
            "Immediate identity check or the example account closes",
            "Final warning: confirm your login or pay by gift card",
            "Account alert that does not come from the real agency",
        ],
        "openers": [
            "This synthetic phish pretends to be a benefits security desk. The tone is alarm, and the instructions are not how a real agency collects a debt.",
            "A fake security team wrote this demonstration lure. It copies the urgency of a real notice and then asks for secrets a real office will not ask for by email.",
            "Read this as a look-alike, built for the dataset so the sorter has a suspicious class. The sender name sounds official and the domain is not.",
            "The following demand is intentionally phish-like. It is labeled so the triage flag can override the action class the wording imitates.",
        ],
        "middles": [
            "The message claims the example benefit was suspended because a login looked unusual. It asks you to type your password and the last four digits of a social security number into a form.",
            "It says the only way to stop collection is a wire transfer or a stack of gift cards sent to a stranger. A real debt letter does not work that way.",
            "The body threatens that the account will be deleted tonight unless you verify your identity and read back a one-time code to someone on the phone.",
            "A bitcoin address is offered as the way to 'clear' a made-up balance. The letter also asks for the example account password.",
        ],
        "closings": [
            "Verify your identity at http://va-benefits.login.example.com/verify within 24 hours. That host is a look-alike used only in this synthetic phish.",
            "Use http://benefits.login.example.com/account before the fake timer ends. The page asks for a password, which is the point of the lure.",
            "The look-alike collection page is http://insurance.verify-now.example.com/pay and it should not be opened. Gift card payment is a cue by itself.",
            "The lure ends at http://mypay.secure-update.example.com/login and tells you the account will be deleted if you wait. Do not follow it.",
        ],
    },
    {
        "notice_type": "phishing_lure",
        "label": "INFORMATIONAL",
        "suspicious": 1,
        "hard_case": "phishing",
        "source": "DFAS",
        "from_addrs": ["Statement Desk <notices@mypay-alerts.example.com>"],
        "subjects": [
            "Your statement is ready, use the new login link",
            "Tax form posted, open the secure-update page",
            "A document is waiting behind a look-alike login",
            "Statement notice with an extra login step",
        ],
        "openers": [
            "This softer lure imitates a statement-ready note. The underlying topic sounds informational, and the link is the trap.",
            "A fake statement desk wrote the demo. It does not shout about a debt. It only offers a document and a login that is not the real one.",
            "The tone is calm, like a 1099 availability note, except the destination is a host built for this phishing example.",
            "Treat the paragraph below as a look-alike of ordinary mail. The class of the topic is informational; the flag is suspicious because of the link.",
        ],
        "middles": [
            "The lure says a retired-pay statement is ready to view and that the usual site is down for the weekend. It suggests a temporary page instead.",
            "It claims the annual tax statement can be saved only from a special host this week. No dollar figure is billed. No threat is spelled with the word suspended.",
            "A short note says the example document list was copied to a partner page so you can download it without waiting. The partner page is not real.",
            "The message mentions that a statement posted and that a one-time viewing link will expire. It does not ask you to pay anything.",
        ],
        "closings": [
            "Open http://mypay.secure-update.example.com/login to see the statement. The host is synthetic and should be treated as suspicious even though no payment is asked.",
            "The document link in this lure is http://benefits.login.example.com/statement and it is not the example myPay site you already use.",
            "Download is offered at http://va-benefits.login.example.com/forms which is a look-alike path created for the dataset.",
            "The viewing page is http://insurance.verify-now.example.com/statement and it rides on a verify-now host that a real receipt would not use.",
        ],
    },
]
